services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
    restart: unless-stopped
