package storage

import (
	"codeShare/internal/models"
	"time"
)

// In-memory storage for snippets (to be replaced with a database later)
var sampleSnippets = []models.Snippet{
	{
		ID:        "1",
		Title:     "Vue 3 Composition API Example",
		Content:   "import { ref, computed } from 'vue'\nexport default {\n    setup() {\n        const count = ref(0)\n        const double = computed(() => count.value * 2)\n\n        function increment() {\n            count.value++\n        }\n\n        return {\n            count,\n            double,\n            increment\n        }\n    }\n}",
		Author:    "John Doe",
		CreatedAt: time.Now().Add(-24 * time.Hour),
		UpdatedAt: time.Now().Add(-24 * time.Hour),
		Likes:     290,
		UserLikes: map[string]bool{
			"current_user": true,
		},
	},
	{
		ID:        "2",
		Title:     "React Hooks: useEffect Example",
		Content:   "import React, { useState, useEffect } from 'react';\n\nfunction Example() {\n    const [count, setCount] = useState(0);\n\n    useEffect(() => {\n    document.title = `Count: ${count}`;\n    });\n\n    return (\n    <div>\n        <p>You clicked {count} times</p>\n        <button onClick={() => setCount(count + 1)}>Click me</button>\n    </div>\n    );\n}",
		Author:    "Alice Johnson",
		CreatedAt: time.Now().Add(-48 * time.Hour),
		UpdatedAt: time.Now().Add(-48 * time.Hour),
		Likes:     104,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "3",
		Title:     "Shell Script Example",
		Content:   "#!/bin/bash\n\necho \"Hello, World!\"",
		Author:    "Paula Cyan",
		CreatedAt: time.Now().Add(-72 * time.Hour),
		UpdatedAt: time.Now().Add(-72 * time.Hour),
		Likes:     17,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "4",
		Title:     "Java Basic Hello World",
		Content:   "public class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println(\"Hello, World!\");\n    }\n}",
		Author:    "Ivy Purple",
		CreatedAt: time.Now().Add(-96 * time.Hour),
		UpdatedAt: time.Now().Add(-96 * time.Hour),
		Likes:     3,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "5",
		Title:     "Go Simple HTTP Server",
		Content:   "package main\n\nimport (\n    \"fmt\"\n    \"net/http\"\n)\n\nfunc handler(w http.ResponseWriter, r *http.Request) {\n    fmt.Fprintf(w, \"Hello, World!\")\n}\n\nfunc main() {\n    http.HandleFunc(\"/\", handler)\n    http.ListenAndServe(\":8080\", nil)\n}",
		Author:    "Grace Yellow",
		CreatedAt: time.Now().Add(-120 * time.Hour),
		UpdatedAt: time.Now().Add(-120 * time.Hour),
		Likes:     561,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "6",
		Title:     "Python Data Analysis with Pandas",
		Content:   "import pandas as pd\n\ndata = {'Name': ['Tom', 'Jerry', 'Mickey'], 'Age': [20, 21, 19]}\ndf = pd.DataFrame(data)\nprint(df.describe())",
		Author:    "Guido van Rossum",
		CreatedAt: time.Now().Add(-144 * time.Hour),
		UpdatedAt: time.Now().Add(-144 * time.Hour),
		Likes:     666,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "7",
		Title:     "TypeScript Generic Function",
		Content:   "function identity<T>(arg: T): T {\n    return arg;\n}\n\n// Usage\nlet output = identity<string>(\"myString\");\nlet output2 = identity<number>(42);",
		Author:    "Anders Hejlsberg",
		CreatedAt: time.Now().Add(-168 * time.Hour),
		UpdatedAt: time.Now().Add(-168 * time.Hour),
		Likes:     423,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "8",
		Title:     "Rust Error Handling",
		Content:   "fn read_file(path: &str) -> Result<String, io::Error> {\n    let mut file = File::open(path)?;\n    let mut contents = String::new();\n    file.read_to_string(&mut contents)?;\n    Ok(contents)\n}",
		Author:    "Graydon Hoare",
		CreatedAt: time.Now().Add(-192 * time.Hour),
		UpdatedAt: time.Now().Add(-192 * time.Hour),
		Likes:     289,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "9",
		Title:     "Docker Compose Example",
		Content:   "version: '3'\nservices:\n  web:\n    build: .\n    ports:\n      - \"5000:5000\"\n  redis:\n    image: redis:alpine\n    ports:\n      - \"6379:6379\"",
		Author:    "Solomon Hykes",
		CreatedAt: time.Now().Add(-216 * time.Hour),
		UpdatedAt: time.Now().Add(-216 * time.Hour),
		Likes:     512,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "10",
		Title:     "SQL Query with JOIN",
		Content:   "SELECT users.name, orders.order_date, products.name\nFROM users\nINNER JOIN orders ON users.id = orders.user_id\nINNER JOIN products ON orders.product_id = products.id\nWHERE orders.order_date > '2024-01-01'\nORDER BY orders.order_date DESC;",
		Author:    "Edgar Codd",
		CreatedAt: time.Now().Add(-240 * time.Hour),
		UpdatedAt: time.Now().Add(-240 * time.Hour),
		Likes:     378,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "11",
		Title:     "Kotlin Coroutine Example",
		Content:   "suspend fun fetchUserData() = coroutineScope {\n    val user = async { userRepository.getUser() }\n    val posts = async { postRepository.getPosts() }\n    UserWithPosts(user.await(), posts.await())\n}",
		Author:    "JetBrains Team",
		CreatedAt: time.Now().Add(-264 * time.Hour),
		UpdatedAt: time.Now().Add(-264 * time.Hour),
		Likes:     245,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "12",
		Title:     "GraphQL Query",
		Content:   "query {\n  user(id: \"123\") {\n    name\n    email\n    posts {\n      title\n      content\n      comments {\n        text\n        author {\n          name\n        }\n      }\n    }\n  }\n}",
		Author:    "Lee Byron",
		CreatedAt: time.Now().Add(-288 * time.Hour),
		UpdatedAt: time.Now().Add(-288 * time.Hour),
		Likes:     189,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "13",
		Title:     "Swift UI View",
		Content:   "struct ContentView: View {\n    @State private var name = \"\"\n    \n    var body: some View {\n        VStack {\n            TextField(\"Enter your name\", text: $name)\n            Text(\"Hello, \\(name)!\")\n                .font(.title)\n        }\n        .padding()\n    }\n}",
		Author:    "Chris Lattner",
		CreatedAt: time.Now().Add(-312 * time.Hour),
		UpdatedAt: time.Now().Add(-312 * time.Hour),
		Likes:     312,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "14",
		Title:     "Elixir Pattern Matching",
		Content:   "defmodule Math do\n  def factorial(0), do: 1\n  def factorial(n) when n > 0 do\n    n * factorial(n - 1)\n  end\nend",
		Author:    "José Valim",
		CreatedAt: time.Now().Add(-336 * time.Hour),
		UpdatedAt: time.Now().Add(-336 * time.Hour),
		Likes:     178,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "15",
		Title:     "C# LINQ Example",
		Content:   "var result = numbers\n    .Where(n => n % 2 == 0)\n    .Select(n => n * n)\n    .OrderByDescending(n => n)\n    .Take(5)\n    .ToList();",
		Author:    "Anders Hejlsberg",
		CreatedAt: time.Now().Add(-360 * time.Hour),
		UpdatedAt: time.Now().Add(-360 * time.Hour),
		Likes:     267,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "16",
		Title:     "Haskell List Comprehension",
		Content:   "primes = [x | x <- [2..], all (\\y -> x `mod` y /= 0) [2..x-1]]\n\n-- Get first 10 prime numbers\ntake 10 primes",
		Author:    "Simon Peyton Jones",
		CreatedAt: time.Now().Add(-384 * time.Hour),
		UpdatedAt: time.Now().Add(-384 * time.Hour),
		Likes:     156,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "17",
		Title:     "Scala Case Class",
		Content:   "case class Person(name: String, age: Int)\n\nval people = List(\n  Person(\"Alice\", 25),\n  Person(\"Bob\", 30),\n  Person(\"Charlie\", 35)\n)\n\nval youngPeople = people.filter(_.age < 30)",
		Author:    "Martin Odersky",
		CreatedAt: time.Now().Add(-408 * time.Hour),
		UpdatedAt: time.Now().Add(-408 * time.Hour),
		Likes:     234,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "18",
		Title:     "PHP Laravel Route",
		Content:   "Route::middleware(['auth'])->group(function () {\n    Route::get('/profile', [ProfileController::class, 'show']);\n    Route::put('/profile', [ProfileController::class, 'update']);\n    Route::delete('/profile', [ProfileController::class, 'destroy']);\n});",
		Author:    "Taylor Otwell",
		CreatedAt: time.Now().Add(-432 * time.Hour),
		UpdatedAt: time.Now().Add(-432 * time.Hour),
		Likes:     198,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "19",
		Title:     "Ruby on Rails Model",
		Content:   "class User < ApplicationRecord\n  has_many :posts, dependent: :destroy\n  has_many :comments\n  \n  validates :email, presence: true, uniqueness: true\n  validates :username, presence: true, length: { minimum: 3 }\n  \n  before_save :normalize_email\n  \n  private\n  \n  def normalize_email\n    self.email = email.downcase.strip\n  end\nend",
		Author:    "David Heinemeier Hansson",
		CreatedAt: time.Now().Add(-456 * time.Hour),
		UpdatedAt: time.Now().Add(-456 * time.Hour),
		Likes:     345,
		UserLikes: make(map[string]bool),
	},
	{
		ID:        "20",
		Title:     "Deno Web Server",
		Content:   "import { serve } from \"https://deno.land/std@0.168.0/http/server.ts\";\n\nconst handler = (req: Request): Response => {\n  const url = new URL(req.url);\n  return new Response(`Hello from ${url.pathname}!`);\n};\n\nserve(handler, { port: 8000 });",
		Author:    "Ryan Dahl",
		CreatedAt: time.Now().Add(-480 * time.Hour),
		UpdatedAt: time.Now().Add(-480 * time.Hour),
		Likes:     278,
		UserLikes: make(map[string]bool),
	},
}