// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: snippets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSnippet = `-- name: CreateSnippet :one
INSERT INTO snippets (
    id,
    title,
    content,
    author
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, title, content, author, created_at, updated_at, likes
`

type CreateSnippetParams struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Author  string `json:"author"`
}

func (q *Queries) CreateSnippet(ctx context.Context, arg CreateSnippetParams) (Snippet, error) {
	row := q.queryRow(ctx, q.createSnippetStmt, createSnippet,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Author,
	)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Likes,
	)
	return i, err
}

const deleteSnippet = `-- name: DeleteSnippet :exec
DELETE FROM snippets
WHERE id = ?
`

func (q *Queries) DeleteSnippet(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSnippetStmt, deleteSnippet, id)
	return err
}

const getSnippet = `-- name: GetSnippet :one
SELECT 
    s.id, s.title, s.content, s.author, s.created_at, s.updated_at, s.likes,
    CASE WHEN ul.user_id IS NOT NULL THEN 1 ELSE 0 END as is_liked,
    u.username as author_username
FROM snippets s
LEFT JOIN user_likes ul ON s.id = ul.snippet_id AND ul.user_id = ?
LEFT JOIN users u ON s.author = u.id
WHERE s.id = ?
`

type GetSnippetParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

type GetSnippetRow struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	Content        string         `json:"content"`
	Author         string         `json:"author"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Likes          int64          `json:"likes"`
	IsLiked        int64          `json:"is_liked"`
	AuthorUsername sql.NullString `json:"author_username"`
}

func (q *Queries) GetSnippet(ctx context.Context, arg GetSnippetParams) (GetSnippetRow, error) {
	row := q.queryRow(ctx, q.getSnippetStmt, getSnippet, arg.UserID, arg.ID)
	var i GetSnippetRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Likes,
		&i.IsLiked,
		&i.AuthorUsername,
	)
	return i, err
}

const getSnippets = `-- name: GetSnippets :many
SELECT 
    s.id, s.title, s.content, s.author, s.created_at, s.updated_at, s.likes,
    CASE WHEN ul.user_id IS NOT NULL THEN 1 ELSE 0 END as is_liked,
    u.username as author_username
FROM snippets s
LEFT JOIN user_likes ul ON s.id = ul.snippet_id AND ul.user_id = ?
LEFT JOIN users u ON s.author = u.id
ORDER BY s.created_at DESC
`

type GetSnippetsRow struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	Content        string         `json:"content"`
	Author         string         `json:"author"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Likes          int64          `json:"likes"`
	IsLiked        int64          `json:"is_liked"`
	AuthorUsername sql.NullString `json:"author_username"`
}

func (q *Queries) GetSnippets(ctx context.Context, userID string) ([]GetSnippetsRow, error) {
	rows, err := q.query(ctx, q.getSnippetsStmt, getSnippets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSnippetsRow{}
	for rows.Next() {
		var i GetSnippetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Author,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Likes,
			&i.IsLiked,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSnippet = `-- name: UpdateSnippet :one
UPDATE snippets
SET 
    title = ?,
    content = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, content, author, created_at, updated_at, likes
`

type UpdateSnippetParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateSnippet(ctx context.Context, arg UpdateSnippetParams) (Snippet, error) {
	row := q.queryRow(ctx, q.updateSnippetStmt, updateSnippet, arg.Title, arg.Content, arg.ID)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Likes,
	)
	return i, err
}
