// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_likes.sql

package db

import (
	"context"
)

const decrementLikesCount = `-- name: DecrementLikesCount :exec
UPDATE snippets 
SET likes = likes - 1 
WHERE id = ?
`

func (q *Queries) DecrementLikesCount(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.decrementLikesCountStmt, decrementLikesCount, id)
	return err
}

const incrementLikesCount = `-- name: IncrementLikesCount :exec
UPDATE snippets 
SET likes = likes + 1 
WHERE id = ?
`

func (q *Queries) IncrementLikesCount(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.incrementLikesCountStmt, incrementLikesCount, id)
	return err
}

const likeSnippet = `-- name: LikeSnippet :exec
INSERT OR IGNORE INTO user_likes (snippet_id, user_id)
VALUES (?, ?)
`

type LikeSnippetParams struct {
	SnippetID string `json:"snippet_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) LikeSnippet(ctx context.Context, arg LikeSnippetParams) error {
	_, err := q.exec(ctx, q.likeSnippetStmt, likeSnippet, arg.SnippetID, arg.UserID)
	return err
}

const unlikeSnippet = `-- name: UnlikeSnippet :exec
DELETE FROM user_likes
WHERE snippet_id = ? AND user_id = ?
`

type UnlikeSnippetParams struct {
	SnippetID string `json:"snippet_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UnlikeSnippet(ctx context.Context, arg UnlikeSnippetParams) error {
	_, err := q.exec(ctx, q.unlikeSnippetStmt, unlikeSnippet, arg.SnippetID, arg.UserID)
	return err
}

const updateLikesCount = `-- name: UpdateLikesCount :exec
UPDATE snippets
SET likes = (
    SELECT COUNT(*)
    FROM user_likes
    WHERE snippet_id = ?
)
WHERE id = ?
`

type UpdateLikesCountParams struct {
	SnippetID string `json:"snippet_id"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateLikesCount(ctx context.Context, arg UpdateLikesCountParams) error {
	_, err := q.exec(ctx, q.updateLikesCountStmt, updateLikesCount, arg.SnippetID, arg.ID)
	return err
}
