// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_saves.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteSavedSnippet = `-- name: DeleteSavedSnippet :exec
DELETE FROM user_saves
WHERE snippet_id = ?1 AND user_id = ?2
`

type DeleteSavedSnippetParams struct {
	SnippetID string `json:"snippet_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteSavedSnippet(ctx context.Context, arg DeleteSavedSnippetParams) error {
	_, err := q.exec(ctx, q.deleteSavedSnippetStmt, deleteSavedSnippet, arg.SnippetID, arg.UserID)
	return err
}

const getSavedSnippets = `-- name: GetSavedSnippets :many
SELECT s.id, s.title, s.language, s.content, s.author, s.created_at, s.updated_at, s.likes, 
    CASE WHEN ul.user_id IS NOT NULL THEN 1 ELSE 0 END as is_liked,
    CASE WHEN us.user_id IS NOT NULL THEN 1 ELSE 0 END as is_saved,
    u.id AS author_id,
    u.username AS author_username,
    u.avatar AS author_avatar
FROM snippets s
LEFT JOIN user_likes ul ON s.id = ul.snippet_id AND ul.user_id = ?1
LEFT JOIN user_saves us ON s.id = us.snippet_id AND us.user_id = ?1
LEFT JOIN users u ON s.author = u.id
WHERE us.user_id = ?1
ORDER BY s.created_at DESC
`

type GetSavedSnippetsRow struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	Language       string         `json:"language"`
	Content        string         `json:"content"`
	Author         string         `json:"author"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Likes          int64          `json:"likes"`
	IsLiked        int64          `json:"is_liked"`
	IsSaved        int64          `json:"is_saved"`
	AuthorID       sql.NullString `json:"author_id"`
	AuthorUsername sql.NullString `json:"author_username"`
	AuthorAvatar   sql.NullString `json:"author_avatar"`
}

func (q *Queries) GetSavedSnippets(ctx context.Context, userID string) ([]GetSavedSnippetsRow, error) {
	rows, err := q.query(ctx, q.getSavedSnippetsStmt, getSavedSnippets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSavedSnippetsRow{}
	for rows.Next() {
		var i GetSavedSnippetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Language,
			&i.Content,
			&i.Author,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Likes,
			&i.IsLiked,
			&i.IsSaved,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSnippet = `-- name: SaveSnippet :exec
INSERT OR IGNORE INTO user_saves (snippet_id, user_id)
VALUES (?1, ?2)
`

type SaveSnippetParams struct {
	SnippetID string `json:"snippet_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) SaveSnippet(ctx context.Context, arg SaveSnippetParams) error {
	_, err := q.exec(ctx, q.saveSnippetStmt, saveSnippet, arg.SnippetID, arg.UserID)
	return err
}
